version: '3.4'
services:
#  Optional
#  alfresco-search-2028-module-share:
#    image: ${docker.share.image}:${alfresco.share.version}
#    environment:
#      REPO_HOST: alfresco-search-2028-module-acs
#      REPO_PORT: 8080
#    ports:
#      - "${share.port}:8080"
  alfresco-search-2028-module-acs:
    image: alfresco-content-services-alfresco-search-2028-module:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-search-2028-module-acs-volume:/usr/local/tomcat/alf_data
    depends_on:
      - alfresco-search-2028-module-postgres
  alfresco-search-2028-module-postgres:
    image: postgres:9.6
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-search-2028-module-db-volume:/var/lib/postgresql/data
  alfresco-search-2028-module-ass:
    image: alfresco/alfresco-search-services:1.4.2
    environment:
      SOLR_ALFRESCO_HOST: alfresco-search-2028-module-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-search-2028-module-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: none
    ports:
      - "8983:8983"
    volumes:
      - alfresco-search-2028-module-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-search-2028-module-ass-volume:/opt/alfresco-search-services/data
volumes:
  alfresco-search-2028-module-acs-volume:
    external: true
  alfresco-search-2028-module-db-volume:
    external: true
  alfresco-search-2028-module-ass-volume:
    external: true
